server:
  port: 8080

spring:
  application:
    name: bootcamp-xp-edu
  mongodb:
    uri: ${ENV_MONGO_DB_URI}
    database: ${ENV_MONGO_DB_DATABASE}
  data:
    mongodb:
      auto-index-creation: true
